# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

env:

  global:
    - LANG='en_US.UTF-8'

  matrix:
    - TEST='1'
    - TEST='pep8'
    - TEST='isort'
    - TEST='docs'

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox virtualenv coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; export TOX_ENV=py26; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export TOX_ENV=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export TOX_ENV=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export TOX_ENV=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export TOX_ENV=py35; fi"
  - "if [[ $TEST != '1' ]]; then export TOX_ENV=$TEST; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run --source=djangocms_installer' tox -e$TOX_ENV

after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 2.6
    env: TEST='pep8'
  - python: 2.6
    env: TEST='isort'
  - python: 2.6
    env: TEST='docs'
  - python: 2.7
    env: TEST='pep8'
  - python: 2.7
    env: TEST='isort'
  - python: 2.7
    env: TEST='docs'
  - python: 3.3
    env: TEST='pep8'
  - python: 3.3
    env: TEST='isort'
  - python: 3.4
    env: TEST='docs'
  - python: 3.4
    env: TEST='pep8'
  - python: 3.4
    env: TEST='isort'
  - python: 3.4
    env: TEST='docs'

notifications:
  webhooks: https://ring.nephila.it/packages/hook/
